name: touch_hallu
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.2=h26f9b46_0
  - pip=25.2=pyh145f28c_0
  - python=3.13.5=hec9711d_102_cp313
  - python_abi=3.13=8_cp313
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_hd72426e_102
  - pip:
      - accelerate==1.10.1
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - attrs==25.4.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==3.6.0
      - diffusers==0.35.2
      - dill==0.3.7
      - distro==1.9.0
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2023.10.0
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - idna==3.10
      - importlib-metadata==8.7.0
      - jinja2==3.1.4
      - jiter==0.10.0
      - kiwisolver==1.4.9
      - markupsafe==3.0.2
      - matplotlib==3.10.7
      - modelscope==1.30.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.15
      - networkx==3.3
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.102.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.17.1
      - pillow==11.0.0
      - propcache==0.4.1
      - protobuf==6.32.1
      - psutil==7.0.0
      - pyarrow==18.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.9.1
      - requests==2.32.5
      - safetensors==0.6.2
      - sentencepiece==0.2.1
      - setuptools==80.9.0
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tokenizers==0.22.0
      - torch==2.6.0+cu124
      - torchtext==0.6.0
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.2.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /data/chengkaiwang/Software/anaconda3/envs/touch_hallu
